// frontend-svelte/src/lib/components/CategoryPicker.svelte
<script>
  /** @type {{ id: string, name: string, color: string }[]} */
  let { categories = [], selectedIds = $bindable([]) } = $props();

  function toggle(id) {
    const s = new Set(selectedIds);
    if (s.has(id)) s.delete(id);
    else s.add(id);
    selectedIds = [...s];
  }
</script>

{#if categories.length === 0}
  <p class="hint">Сначала создайте категории на вкладке «Категории».</p>
{:else}
  <div class="cat-grid">
    {#each categories as cat (cat.id)}
      <button
        type="button"
        class="cat-chip"
        class:selected={selectedIds.includes(cat.id)}
        onclick={() => toggle(cat.id)}
      >
        <span class="dot" style="background: {cat.color}"></span>
        <span class="name">{cat.name}</span>
      </button>
    {/each}
  </div>
{/if}

<style>
  .hint {
    margin: 0;
    font-size: 13px;
    color: var(--text-muted);
    line-height: 1.4;
  }
  .cat-grid {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
  }
  .cat-chip {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    padding: 8px 12px;
    border-radius: 999px;
    border: 1px solid var(--border);
    background: var(--surface);
    cursor: pointer;
    font: inherit;
    font-size: 13px;
    color: var(--text);
    transition: border-color 0.15s, background 0.15s, box-shadow 0.15s;
  }
  .cat-chip:hover {
    border-color: color-mix(in srgb, var(--primary) 35%, var(--border));
  }
  .cat-chip.selected {
    border-color: var(--primary);
    background: color-mix(in srgb, var(--primary) 10%, white);
    box-shadow: 0 0 0 1px color-mix(in srgb, var(--primary) 25%, transparent);
  }
  .dot {
    width: 10px;
    height: 10px;
    border-radius: 50%;
    flex-shrink: 0;
  }
  .name {
    font-weight: 500;
  }
</style>

// frontend-react/src/components/CategoryPicker.jsx
export function CategoryPicker({ categories = [], selectedIds, onChange }) {
  function toggle(id) {
    const s = new Set(selectedIds)
    if (s.has(id)) s.delete(id)
    else s.add(id)
    onChange([...s])
  }

  if (!categories.length) {
    return (
      <p style={{ margin: 0, fontSize: 13, color: 'var(--text-muted)' }}>
        Сначала создайте категории на вкладке «Категории».
      </p>
    )
  }

  return (
    <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
      {categories.map((cat) => {
        const selected = selectedIds.includes(cat.id)
        return (
          <button
            key={cat.id}
            type="button"
            onClick={() => toggle(cat.id)}
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: 8,
              padding: '8px 12px',
              borderRadius: 999,
              border: `1px solid ${selected ? 'var(--primary)' : 'var(--border)'}`,
              background: selected ? 'color-mix(in srgb, var(--primary) 10%, var(--surface))' : 'var(--surface)',
              cursor: 'pointer',
              font: 'inherit',
              fontSize: 13,
              color: 'var(--text)',
              boxShadow: selected ? '0 0 0 1px color-mix(in srgb, var(--primary) 22%, transparent)' : 'none',
            }}
          >
            <span
              style={{
                width: 10,
                height: 10,
                borderRadius: '50%',
                background: cat.color,
                flexShrink: 0,
              }}
            />
            <span style={{ fontWeight: 500 }}>{cat.name}</span>
          </button>
        )
      })}
    </div>
  )
}
